### ISSUE TITLE
How to host this application yourself

### ISSUE THREAD

**Issue by golfsheet** [jpf/TwilioSheet#5]
Can you post a tutorial on how to host the application yourself?  I am able to host the python flask on heroku, but I'm not sure how to configure it to my google form settings.

**Comment by jpf** [comment]
Hi there @golfsheet, the version of TwilioSheet on my GitHub page isn't current anymore. @devinrader has an updated version that will work with the new version of Google Spreadsheets: https://github.com/devinrader/twiliosheet

As far as hosting it yourself, you just need to deploy it to Heroku. Here is an in-depth guide for pushing Flask apps to Heroku: https://devcenter.heroku.com/articles/getting-started-with-python#deploy-the-app

You won't need to configure any Google Form settings, since all of the important data is "stored" in the URL that you configure with Twilio.

**Comment by golfsheet** [comment]
Thanks jpf!  I'll take a look.
